# 개발계 DB 접속정보
spring.datasource.url=jdbc:postgresql://localhost:5432/ExpenseTracker
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# 개발계 첨부파일 저장 경로
app.file.upload-dir=D:/workspace/files

# 템플릿/정적리소스를 소스 폴더에서 직접 로딩 (build 복사 없이 새로고침만으로 반영)
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.static-locations=file:src/main/resources/static/,classpath:/static/
