spring.application.name=expenseTracker

spring.datasource.url=jdbc:postgresql://localhost:5432/ExpenseTracker
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

# \uC2DC\uC2A4\uD15C \uB85C\uADF8 \uCD5C\uC18C \uC800\uC7A5 \uB808\uBCA8 (DEBUG < INFO < WARNING < ERROR)
app.log.min-level=INFO

