-- LOGLEVEL 코드그룹 등록
INSERT INTO TB_CO_CODE_GROUP (GROUP_ID, GROUP_NM, RGS_DT, RGS_USER_ID)
VALUES ('LOGLEVEL', '로그레벨', CURRENT_TIMESTAMP, 'admin')
ON CONFLICT (GROUP_ID) DO NOTHING;

-- LOGLEVEL 코드 등록
INSERT INTO TB_CO_CODE (CODE_ID, GROUP_ID, CODE_NM, SORT_SN, USE_AT, RGS_DT, RGS_USER_ID)
VALUES
  ('LOGLEVEL_001', 'LOGLEVEL', 'INFO',    1, 'Y', CURRENT_TIMESTAMP, 'admin'),
  ('LOGLEVEL_002', 'LOGLEVEL', 'DEBUG',   2, 'Y', CURRENT_TIMESTAMP, 'admin'),
  ('LOGLEVEL_003', 'LOGLEVEL', 'ERROR',   3, 'Y', CURRENT_TIMESTAMP, 'admin'),
  ('LOGLEVEL_004', 'LOGLEVEL', 'WARNING', 4, 'Y', CURRENT_TIMESTAMP, 'admin')
ON CONFLICT (CODE_ID, GROUP_ID) DO NOTHING;
