-- ============================================================
-- PostgreSQL
-- ============================================================
CREATE TABLE TB_CO_USER (
  USER_ID      VARCHAR(36)  NOT NULL,
  LOGIN_ID     VARCHAR(50)  NOT NULL,
  PASSWD       VARCHAR(200) NOT NULL,
  USER_NM      VARCHAR(100) NOT NULL,
  NICKNAME     VARCHAR(100),
  EMAIL        VARCHAR(200),
  ROLE_CD      VARCHAR(30),
  USE_AT       VARCHAR(1)   DEFAULT 'Y',
  DEL_AT       VARCHAR(1)   DEFAULT 'N',
  RGS_DT       TIMESTAMP,
  RGS_USER_ID  VARCHAR(30),
  UPD_DT       TIMESTAMP,
  UPD_USER_ID  VARCHAR(30),
  CONSTRAINT pk_tb_co_user          PRIMARY KEY (USER_ID),
  CONSTRAINT uk_tb_co_user_login_id UNIQUE (LOGIN_ID),
  CONSTRAINT uk_tb_co_user_email    UNIQUE (EMAIL)
);

COMMENT ON TABLE  TB_CO_USER             IS '사용자';
COMMENT ON COLUMN TB_CO_USER.USER_ID     IS '사용자ID (UUID)';
COMMENT ON COLUMN TB_CO_USER.LOGIN_ID    IS '로그인ID';
COMMENT ON COLUMN TB_CO_USER.PASSWD      IS '비밀번호';
COMMENT ON COLUMN TB_CO_USER.USER_NM     IS '사용자명';
COMMENT ON COLUMN TB_CO_USER.NICKNAME    IS '닉네임';
COMMENT ON COLUMN TB_CO_USER.EMAIL       IS '이메일';
COMMENT ON COLUMN TB_CO_USER.ROLE_CD     IS '권한코드 (공통코드 ROLE 그룹 참조)';
COMMENT ON COLUMN TB_CO_USER.USE_AT      IS '사용여부';
COMMENT ON COLUMN TB_CO_USER.DEL_AT      IS '삭제여부';
COMMENT ON COLUMN TB_CO_USER.RGS_DT      IS '등록일시';
COMMENT ON COLUMN TB_CO_USER.RGS_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TB_CO_USER.UPD_DT      IS '수정일시';
COMMENT ON COLUMN TB_CO_USER.UPD_USER_ID IS '수정사용자ID';
