-- ============================================================
-- PostgreSQL
-- ============================================================
CREATE TABLE TB_CO_USER_CONSENT (
  CONSENT_ID   VARCHAR(36)  NOT NULL,
  USER_ID      VARCHAR(36)  NOT NULL,
  CONSENT_TYPE VARCHAR(20)  NOT NULL,
  AGREED       VARCHAR(1)   NOT NULL,
  AGREED_AT    TIMESTAMPTZ  NOT NULL,
  CONSTRAINT pk_tb_co_user_consent      PRIMARY KEY (CONSENT_ID),
  CONSTRAINT fk_tb_co_user_consent_user FOREIGN KEY (USER_ID) REFERENCES TB_CO_USER (USER_ID)
);

CREATE INDEX ix_tb_co_user_consent_user_id ON TB_CO_USER_CONSENT (USER_ID);

COMMENT ON TABLE  TB_CO_USER_CONSENT              IS '사용자 동의이력';
COMMENT ON COLUMN TB_CO_USER_CONSENT.CONSENT_ID   IS '동의이력ID (UUID)';
COMMENT ON COLUMN TB_CO_USER_CONSENT.USER_ID      IS '사용자ID';
COMMENT ON COLUMN TB_CO_USER_CONSENT.CONSENT_TYPE IS '동의유형 (TERMS/PRIVACY/MARKETING)';
COMMENT ON COLUMN TB_CO_USER_CONSENT.AGREED       IS '동의여부 (Y/N)';
COMMENT ON COLUMN TB_CO_USER_CONSENT.AGREED_AT    IS '동의일시';
