-- ============================================================
-- PostgreSQL
-- ============================================================
CREATE TABLE TB_CO_FILES (
  FILE_GROUP_ID VARCHAR(36)    NOT NULL,
  FILE_ID       VARCHAR(36)    NOT NULL,
  ORG_FILE_NM   VARCHAR(255)   NOT NULL,
  SAVE_FILE_NM  VARCHAR(255)   NOT NULL,
  FILE_PATH     VARCHAR(500)   NOT NULL,
  FILE_SIZE     NUMERIC(15, 0),
  FILE_EXT      VARCHAR(20),
  SORT_SN       NUMERIC(10, 0),
  DEL_AT        VARCHAR(1)     DEFAULT 'N',
  RGS_DT        TIMESTAMP,
  RGS_USER_ID   VARCHAR(36),
  CONSTRAINT pk_tb_co_files PRIMARY KEY (FILE_GROUP_ID, FILE_ID)
);

COMMENT ON TABLE  TB_CO_FILES               IS '공통 첨부파일';
COMMENT ON COLUMN TB_CO_FILES.FILE_GROUP_ID IS '파일그룹ID';
COMMENT ON COLUMN TB_CO_FILES.FILE_ID       IS '파일ID (UUID)';
COMMENT ON COLUMN TB_CO_FILES.ORG_FILE_NM   IS '원본파일명';
COMMENT ON COLUMN TB_CO_FILES.SAVE_FILE_NM  IS '저장파일명';
COMMENT ON COLUMN TB_CO_FILES.FILE_PATH     IS '저장경로';
COMMENT ON COLUMN TB_CO_FILES.FILE_SIZE     IS '파일크기(byte)';
COMMENT ON COLUMN TB_CO_FILES.FILE_EXT      IS '확장자';
COMMENT ON COLUMN TB_CO_FILES.SORT_SN       IS '정렬순번';
COMMENT ON COLUMN TB_CO_FILES.DEL_AT        IS '삭제여부';
COMMENT ON COLUMN TB_CO_FILES.RGS_DT        IS '등록일시';
COMMENT ON COLUMN TB_CO_FILES.RGS_USER_ID   IS '등록사용자ID';
