-- ============================================================
-- PostgreSQL
-- ============================================================
CREATE TABLE TB_EX_FIXED_EXPENSE (
  FIXED_EXPENSE_ID  BIGSERIAL      NOT NULL,
  USER_ID           VARCHAR(36)    NOT NULL,
  PAYMENT_METHOD_CD VARCHAR(30),
  EXPENSE_CYCLE_CD  VARCHAR(30),
  CATEGORY_CD       VARCHAR(30),
  ANCHOR_DT         DATE           NOT NULL,
  AMOUNT            NUMERIC(15, 2) NOT NULL,
  CONTENT           VARCHAR(200)   NOT NULL,
  MEMO              VARCHAR(500),
  FILE_GROUP_ID     VARCHAR(36),
  USE_AT            VARCHAR(1)     DEFAULT 'Y',
  DEL_AT            VARCHAR(1)     DEFAULT 'N',
  RGS_DT            TIMESTAMP,
  RGS_USER_ID       VARCHAR(36),
  UPD_DT            TIMESTAMP,
  UPD_USER_ID       VARCHAR(36),
  CONSTRAINT pk_tb_ex_fixed_expense      PRIMARY KEY (FIXED_EXPENSE_ID),
  CONSTRAINT fk_tb_ex_fixed_expense_user FOREIGN KEY (USER_ID) REFERENCES TB_CO_USER (USER_ID)
);

CREATE INDEX ix_tb_ex_fixed_expense_user_id ON TB_EX_FIXED_EXPENSE (USER_ID);

COMMENT ON TABLE  TB_EX_FIXED_EXPENSE                  IS '고정지출';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.FIXED_EXPENSE_ID IS '고정지출ID';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.USER_ID           IS '사용자ID';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.PAYMENT_METHOD_CD IS '결제수단코드 (공통코드 PAYMENTMETHOD 그룹 참조)';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.EXPENSE_CYCLE_CD  IS '지출주기코드 (공통코드 EXPENSECYCLE 그룹 참조)';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.CATEGORY_CD       IS '카테고리코드 (공통코드 CATEGORY 그룹 참조)';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.ANCHOR_DT          IS '기준일(시작일) (다음 지출 예정일 계산 기준. 매주/격주는 요일, 매월 계열은 일자, 매년은 월일을 이 날짜에서 추출)';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.AMOUNT             IS '금액';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.CONTENT            IS '내용';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.MEMO               IS '메모';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.FILE_GROUP_ID      IS '첨부파일그룹ID (TB_CO_FILES 참조)';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.USE_AT             IS '사용여부';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.DEL_AT             IS '삭제여부';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.RGS_DT             IS '등록일시';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.RGS_USER_ID        IS '등록사용자ID';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.UPD_DT             IS '수정일시';
COMMENT ON COLUMN TB_EX_FIXED_EXPENSE.UPD_USER_ID        IS '수정사용자ID';
