-- ============================================================
-- PostgreSQL — 최초 생성
-- ============================================================
CREATE TABLE TB_SYS_LOGS (
  LOG_ID       BIGSERIAL       NOT NULL,
  LOG_DT       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LOG_LEVEL_CD VARCHAR(30)     NOT NULL,
  USER_ID      VARCHAR(50),
  HTTP_METHOD  VARCHAR(10)     NOT NULL,
  REQUEST_URI  VARCHAR(500),
  HTTP_STATUS  SMALLINT,
  RESPONSE_MS  INT,
  ERROR_MSG    VARCHAR(1000),
  CLIENT_IP    VARCHAR(45),
  CONSTRAINT pk_tb_sys_logs PRIMARY KEY (LOG_ID)
);

CREATE INDEX idx_sys_logs_01 ON TB_SYS_LOGS (LOG_DT DESC);
CREATE INDEX idx_sys_logs_02 ON TB_SYS_LOGS (LOG_LEVEL_CD);
CREATE INDEX idx_sys_logs_03 ON TB_SYS_LOGS (HTTP_STATUS);

COMMENT ON TABLE  TB_SYS_LOGS              IS '시스템로그';
COMMENT ON COLUMN TB_SYS_LOGS.LOG_ID       IS '로그ID';
COMMENT ON COLUMN TB_SYS_LOGS.LOG_DT       IS '로그일시';
COMMENT ON COLUMN TB_SYS_LOGS.LOG_LEVEL_CD IS '로그레벨코드';
COMMENT ON COLUMN TB_SYS_LOGS.USER_ID      IS '사용자ID';
COMMENT ON COLUMN TB_SYS_LOGS.HTTP_METHOD  IS 'HTTP메서드(GET/POST/PUT/DELETE)';
COMMENT ON COLUMN TB_SYS_LOGS.REQUEST_URI  IS '요청URI';
COMMENT ON COLUMN TB_SYS_LOGS.HTTP_STATUS  IS 'HTTP응답상태코드';
COMMENT ON COLUMN TB_SYS_LOGS.RESPONSE_MS  IS '처리시간(ms)';
COMMENT ON COLUMN TB_SYS_LOGS.ERROR_MSG    IS '에러메시지';
COMMENT ON COLUMN TB_SYS_LOGS.CLIENT_IP    IS '클라이언트IP';

-- ============================================================
-- 기존 테이블 마이그레이션 (이미 TB_SYS_LOGS 가 존재하는 경우)
-- ============================================================
-- ALTER TABLE TB_SYS_LOGS DROP COLUMN IF EXISTS ACTION_CD;
-- ALTER TABLE TB_SYS_LOGS DROP COLUMN IF EXISTS ENDPOINT;
-- ALTER TABLE TB_SYS_LOGS DROP COLUMN IF EXISTS DETAIL;
-- ALTER TABLE TB_SYS_LOGS ADD COLUMN IF NOT EXISTS HTTP_METHOD VARCHAR(10);
-- ALTER TABLE TB_SYS_LOGS ADD COLUMN IF NOT EXISTS REQUEST_URI VARCHAR(500);
-- ALTER TABLE TB_SYS_LOGS ADD COLUMN IF NOT EXISTS HTTP_STATUS SMALLINT;
-- ALTER TABLE TB_SYS_LOGS ADD COLUMN IF NOT EXISTS RESPONSE_MS INT;
-- ALTER TABLE TB_SYS_LOGS ADD COLUMN IF NOT EXISTS ERROR_MSG   VARCHAR(1000);
-- ALTER TABLE TB_SYS_LOGS ADD COLUMN IF NOT EXISTS CLIENT_IP   VARCHAR(45);
